GestorProyectoWeb/Models/Proyecto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GestorProyectoWeb.Models
{
    [Table("Proyecto")]
    public class Proyecto
    {
        public Proyecto()
        {
            Tareas = new HashSet<Tarea>();
        }

        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "No ingreso el nombre")]
        [Display(Name = "Nombre del Proyecto")]
        [StringLength(30)]
        public string Nombre { get; set; }

        [StringLength(300)]
        public string Descripcion { get; set; }

        [Required]
        //[DataType(DataType.Date)]
        [Display(Name = "Fecha de Inicio")]
        public DateTime FechaInicio { get; set; }

        public virtual List<Usuario> Usuarios { get; set; }

        public EnumTipoUsuario   TiposUsuarios { get; set; }

        public virtual ICollection<Tarea> Tareas { get; set; }
    }
}

GestorProyectoWeb/Controllers/ProyectoController.cs
using GestorProyectoWeb.Models;
using GestorProyectoWeb.Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestorProyectoWeb.Controllers
{
    public class ProyectoController : Controller
    {
        private Repositorio _repositorio;
        
        
        public ProyectoController()
        {
            _repositorio = new Repositorio();
        }

        // GET: Proyecto
        public ActionResult Index()
        {
            var proyectos = _repositorio.ObtenerProyectos();
            return View(proyectos);
        }

        // GET: Proyecto/Details/5
        public ActionResult Details(int id)
        {
            var proyecto = _repositorio.BuscarProyecto(id);
            return View(proyecto);
        }

        // GET: Proyecto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proyecto/Create
        [HttpPost]
        public ActionResult Create(Proyecto proyecto)
        {
            try
            {
                   _repositorio.GuardarProyecto(proyecto);
            }
            catch (Exception ex)
            {

                return View();
            }

            return RedirectToAction("Index");
        }

        // GET: Proyecto/Edit/5
        public ActionResult Edit(int id)
        {
            Proyecto p = _repositorio.BuscarProyecto(id);
            return View(p);
        }

        // POST: Proyecto/Edit/5
        [HttpPost]
        public ActionResult Edit(Proyecto p)
        {
            try
            {
                // TODO: Add update logic here
                _repositorio.ModificarProyecto(p);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Proyecto/Delete/5
        public ActionResult Delete(int id)
        {
            var proyecto = _repositorio.BuscarProyecto(id);
            return View(proyecto);
        }

        // POST: Proyecto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                _repositorio.EliminarProyecto(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestorProyectoWeb/Controllers/TareaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestorProyectoWeb.Servicios;
using GestorProyectoWeb.Models;

namespace GestorProyectoWeb.Controllers
{
    public class TareaController : Controller
    {
        private readonly Repositorio _repositorio;

        public TareaController()
        {
            _repositorio = new Repositorio();
        }


        // GET: Tarea
        public ActionResult Index()
        {
            return View();
        }

        // GET: Tarea/Details/5
        public ActionResult Details(int id)
        {
            var tarea= _repositorio.BuscarTarea(id);
            return View(tarea);
        }

        // GET: Tarea/Create
        public ActionResult Create(int id)
        {
            var pro = new Proyecto { Id = id };
            ViewBag.Proyecto = pro;

            return View();
        }

        // POST: Tarea/Create
        [HttpPost]
        public ActionResult Create(Tarea tarea, int id)
        {
            try
            {
                // TODO: Add insert logic here
                var pro = new Proyecto { Id = id };
                ViewBag.Proyecto = pro;

                _repositorio.GuardarTarea(tarea, id);
                return RedirectToRoute(new
                {
                    controller = "Proyecto",
                    action = "Details",
                    id = id
                });
            }
            catch
            {
                return View();
            }
        }

        // GET: Tarea/Edit/5
        public ActionResult Edit(int id)
        {
            
            var tarea = _repositorio.BuscarTarea(id);
            return View(tarea);
        }

        // POST: Tarea/Edit/5
        [HttpPost]
        public ActionResult Edit(Tarea tarea,int id)
        {
            try
            {
                // TODO: Add update logic here

              

                _repositorio.ModificarTarea(tarea);
                return RedirectToRoute(new
                {
                    controller = "Proyecto",
                    action = "Details",
                    id = id
                });
            }
            catch
            {
                return View();
            }
        }

        // GET: Tarea/Delete/5

        public ActionResult Delete(int id)
        {
           
            var tarea = _repositorio.BuscarTarea(id);

            ViewBag.id = tarea.ProyectoId;
           
            return View(tarea);
        }

        // POST: Tarea/Delete/5
        [HttpPost]
        public ActionResult Delete(Tarea tarea, int id)
        {
            try
            {
                // TODO: Add delete logic here

                _repositorio.EliminarTarea(tarea.IdTarea);
                return RedirectToRoute(new
                {
                    controller = "Proyecto",
                    action = "Details",
                    id = id
                });

            }
            catch
            {
                return View();
            }
        }
    }
}

GestorProyectoWeb/Views/Proyecto/Create.cshtml
@model GestorProyectoWeb.Models.Proyecto 

@{
    ViewBag.Title = "Create";
}

<h2>Crear Nuevo Proyecto</h2>

@using (Html.BeginForm())
{
    

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Proyecto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @(Html.LabelFor(model => model.FechaInicio, "Fecha de Inicio", htmlAttributes: new { @class = "control-label col-md-2" } ))
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaInicio, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Vover", "Index")
</div>

GestorProyectoWeb/Views/Proyecto/Delete.cshtml
@model GestorProyectoWeb.Models.Proyecto

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Estas seguro que quieres eliminar el proyecto?</h3>
<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

    </dl>

    <h4>Tareas</h4>

    <table class="table">
        <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Fecha Fin</th>
            <th></th>
        </tr>

        @foreach (var item in Model.Tareas)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaInicio)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", "Tarea", new { id = item.IdTarea }, null) |
                    @Html.ActionLink("Detalles", "Details", "Tarea", new { id = item.IdTarea }, null) |
                    @Html.ActionLink("Eliminar", "Delete", "Tarea", new { id = item.IdTarea }, null)
                </td>
            </tr>
        }
    </table>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Volver", "Index")
        </div>
    }
</div>

GestorProyectoWeb/Views/Proyecto/Details.cshtml
@model GestorProyectoWeb.Models.Proyecto

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

    </dl>
    <hr />
    
    <h4>Tareas</h4> 

    <div class="col-md-offset-10 col-md-10">
        @Html.ActionLink("Agregar Tarea", "Create", "Tarea", new { id = Model.Id}, null)
    </div>

    <table class="table">
        <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Fecha Fin</th>
            <th></th>
        </tr>

    @foreach (var item in Model.Tareas)
    {
        <tr>
            <td>
               @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", "Tarea", new { id = item.IdTarea }, null) |
                @Html.ActionLink("Detalles", "Details", "Tarea", new { id = item.IdTarea }, null) |
                @Html.ActionLink("Eliminar", "Delete", "Tarea",  new { id = item.IdTarea }, null)
            </td>
        </tr>
    }
    </table>

</div>
<p>
    @Html.ActionLink("Volver", "Index")
</p>

GestorProyectoWeb/Views/Proyecto/Edit.cshtml
@model GestorProyectoWeb.Models.Proyecto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.Be ginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proyecto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaInicio.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GestorProyectoWeb/Views/Proyecto/Index.cshtml
@model IEnumerable<GestorProyectoWeb.Models.Proyecto>

@{
    ViewBag.Title = "Index";
}

<h2>Proyectos</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaInicio)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>