GestorProyectoWeb/Controllers/RecursoHardwareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestorProyectoWeb.Servicios;
using GestorProyectoWeb.Models;

namespace GestorProyectoWeb.Controllers
{
    public class RecursoHardwareController : Controller
    {
        private readonly Repositorio _repositorio;

        public RecursoHardwareController()
        {
            _repositorio = new Repositorio();
        }

        // GET: RecursoHardware
        public ActionResult Index()
        {
            var recursos = _repositorio.ObtenerRecursoHardware();
            return View(recursos);
        }

        // GET: RecursoHardware/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RecursoHardware/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RecursoHardware/Create
        [HttpPost]
        public ActionResult Create(RecursoHardware recurso)
        {
            try
            {
                // TODO: Add insert logic here

                _repositorio.GuardarRecurso(recurso);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RecursoHardware/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RecursoHardware/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RecursoHardware/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RecursoHardware/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestorProyectoWeb/Controllers/RecursoHumanoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestorProyectoWeb.Servicios;
using GestorProyectoWeb.Models;

namespace GestorProyectoWeb.Controllers
{
    public class RecursoHumanoController : Controller
    {
        private readonly Repositorio _repositorio;

        public RecursoHumanoController()
        {
            _repositorio = new Repositorio();
        }

        // GET: RecursoHumano
        public ActionResult Index()
        {
            var recursos = _repositorio.ObtenerRecursosHumano();
            return View(recursos);
        }

        // GET: RecursoHumano/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RecursoHumano/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RecursoHumano/Create
        [HttpPost]
        public ActionResult Create(RecursoHumano recurso)
        {
            try
            {
                // TODO: Add insert logic here
                _repositorio.GuardarRecurso(recurso);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RecursoHumano/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RecursoHumano/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RecursoHumano/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RecursoHumano/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestorProyectoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gestor Proyecto", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--Parametros: Nombre que figura en la vista, Nombre de la accion, Nombre del controlador-->
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li> 
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Proyecto", "Index", "Proyecto")</li>
                    <li class="dropdown-toggle" data-toggle="dropdown">@Html.ActionLink("Recurso", "Index", "Recurso")</li>
                    <ul class="dropdown-menu pt-xl-5">
                        <li>@Html.ActionLink("Hardware", "Index", "RecursoHardware")</li>
                        <li>@Html.ActionLink("Software", "Index", "RecursoSoftware")</li>
                        <li>@Html.ActionLink("Humano", "Index", "RecursoHumano")</li>
                    </ul>   
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li>@Html.ActionLink("Log in", "Index", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - UTN-FRT Gestor de Proyecto</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GestorProyectoWeb/Views/Shared/_LayoutAdministrador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Administrar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--Parametros: Nombre que figura en la vista, Nombre de la accion dentro del controlador, Nombre del controlador-->
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Usuario", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Proyecto", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li>@Html.ActionLink("Log in", "Index", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - UTN-FRT Gestor de Proyecto</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>